version: "3.8"

services:
    nginx:
        image: nginx:latest
        ports:
            - "81:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app1
            - app2
        networks:
            - frontend
            - backend
        restart: always

    app1:
        build:
            context: ./app1
        expose:
            - "8080"
        networks:
            - backend
        restart: always

    app2:
        build:
            context: ./app2
        expose:
            - "8080"
        networks:
            - backend
        restart: always

networks:
    frontend:
    backend:
